name: "Automerge PRs"
description: 'Automatically merges PR that are labelled appropriately and "clean"'
author: "Material-UI team"
inputs:
  repoToken:
    description: "Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true
  mergeLabel:
    description: "Name of the label which indicates we should merge"
    required: true
  mergeMethod:
    description: 'Either "squash" or "merge" or "rebase"'
    required: true
  failedLabel:
    description: "Name of the label which indicates that the PR needs to be updated"
    required: true
runs:
  using: "node12"
  main: "dist/automerge.js"
