name: "Maintenance"
on:
  push:
    branches:
      - master
  #pull_request:
  #  types: [labeled, unlabeled]
  #schedule:
  #  - cron: "*/2 * * * *"

jobs:
  check-pr-state:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: check if prs are dirty
        uses: "./.github/actions/automerge"
        with:
          dirtyLabel: "PR: needs rebase"
          removeOnDirtyLabel: "PR: ready to ship"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
  ship-prs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge ready PRs
        uses: "./.github/actions/automerge"
        with:
          mergeLabel: "PR: ready to ship"
          mergeMethod: "squash"
          dirtyLabel: "PR: needs rebase"
          failedLabel: "PR: needs revision"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
