name: "Maintenance"
on:
  pull_request:
    types: [labeled, unlabeled]
  #schedule:
  #- cron: "*/2 * * * *"

jobs:
  ship-prs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge ready PRs
        uses: "./.github/actions/automerge"
        with:
          mergeLabel: "PR: ready to ship"
          mergeMethod: "squash"
          failedLabel: "PR: needs rebase"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
