name: "Maintenance"
on:
  issues:
    types: [labeled, unlabeled]
  #schedule:
  #- cron: "*/2 * * * *"

jobs:
  ship-prs:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: merge ready PRs
      uses: "./.github/actions/automerge"
      with:
        mergeLabel: "PR: ready to ship"
        mergeMethod: "squash"
        failedLabel: "PR: needs rebase"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
